/**
 *
 * $Id$
 */
package ContenuPedagogique.validation;

import ContenuPedagogique.Enseignant;
import ContenuPedagogique.Formation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ContenuPedagogique.Departement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DepartementValidator {
	boolean validate();

	boolean validateNom(String value);
	boolean validateEnseignants(EList<Enseignant> value);
	boolean validateFormations(EList<Formation> value);
	boolean validateDescription(String value);
	boolean validateDirige(Enseignant value);
	boolean validateTelDept(String value);
	boolean validatePOBoxDept(String value);
	boolean validateAcces(String value);
}
