/**
 *
 * $Id$
 */
package ContenuPedagogique.validation;

import ContenuPedagogique.Departement;
import ContenuPedagogique.Niveau;
import ContenuPedagogique.TypeGRADE;
import ContenuPedagogique.Ue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ContenuPedagogique.Enseignant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnseignantValidator {
	boolean validate();

	boolean validateResponsable(Niveau value);
	boolean validateNom(String value);
	boolean validateEnseigne(EList<Ue> value);
	boolean validateChef(Departement value);
	boolean validateEmail(String value);
	boolean validateBureau(String value);

	boolean validateGrade(TypeGRADE value);
}
