/**
 *
 * $Id$
 */
package ContenuPedagogique.validation;

import ContenuPedagogique.TypePROGR;

/**
 * A sample validator interface for {@link ContenuPedagogique.Programmation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProgrammationValidator {
	boolean validate();

	boolean validateType(TypePROGR value);
	boolean validateJour(String value);
	boolean validateHeure(String value);
	boolean validateSalle(String value);
}
